version: '3.7'

services:
  traefik:
    image: traefik:2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true" 
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=INFO"
    ports:
      - "80:80"       
      - "8080:8080"   
    networks:
      - traefik_webgateway
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  traefik_webgateway:
    external: true